worker-threads: 4
worker-fs-threads: 2
worker-mon-threads: 2

logger-level: debug

stand-alone: true
is-testing: false

server-port: 8080
chat-port: 8081

dbconnection: 'postgresql://bifrost_user:password@localhost:5432/bifrost_db_1'
