components_manager:
  task_processors:
    main-task-processor:
      worker_threads: $worker-threads
    fs-task-processor:
      worker_threads: $worker-fs-threads
    admin-task-processor:
      worker_threads: $worker-mon-threads
      thread_name: mon-worker
  default_task_processor: main-task-processor

  components:
    server:
      listener:
        port: $server-port
        port#fallback: 8080
        task_processor: admin-task-processor

    socket-manager:
      task_processor: main-task-processor         # Run socket accepts on CPU bound task processor
      sockets_task_processor: main-task-processor # Run ProcessSocket() for each new socket on CPU bound task processor
      port: $chat-port
#      port#fallback: 8081

    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: $logger-level
          overflow_behavior: discard

    dynamic-config:
      defaults:
        HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
        POSTGRES_DEFAULT_COMMAND_CONTROL:
          network_timeout_ms: 750
          statement_timeout_ms: 500

    testsuite-support: { }

    http-client:
      load-enabled: $is-testing
      fs-task-processor: fs-task-processor

    tests-control:
      load-enabled: $is-testing
      path: /tests/{action}
      method: POST
      task_processor: main-task-processor

    handler-ping:
      path: /ping
      method: GET
      task_processor: main-task-processor
      throttling_enabled: false
      url_trailing_slash: strict-match

    application:
      load-enabled: true

    registry:
      load-enabled: true
#      stand-alone: $stand-alone

    auth-manager:
      load-enabled: true
#      stand-alone: $stand-alone


    postgres-db-1:
      dbconnection: $dbconnection
      dbconnection#env: DB_CONNECTION
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: false
      connlimit_mode: manual

    handler-server-monitor:
      path: /service/monitor
      method: GET
      task_processor: admin-task-processor
      monitor-handler: false

    dns-client:
      fs-task-processor: fs-task-processor
